package es.pixel.bingo.model.entities;

public enum Imagen {
    MULA_T2("https://render.albiononline.com/v1/item/T2_MOUNT_MULE.png"),
    CABALLO_T3("https://render.albiononline.com/v1/item/T3_MOUNT_HORSE.png"),
    CABALLO_T4("https://render.albiononline.com/v1/item/T4_MOUNT_HORSE.png"),
    CABALLO_T5("https://render.albiononline.com/v1/item/T5_MOUNT_HORSE.png"),
    CABALLO_T6("https://render.albiononline.com/v1/item/T6_MOUNT_HORSE.png"),
    CABALLO_T7("https://render.albiononline.com/v1/item/T7_MOUNT_HORSE.png"),
    CABALLO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_HORSE.png"),
    BUEY_T3("https://render.albiononline.com/v1/item/T3_MOUNT_OX.png"),
    BUEY_T4("https://render.albiononline.com/v1/item/T4_MOUNT_OX.png"),
    BUEY_T5("https://render.albiononline.com/v1/item/T5_MOUNT_OX.png"),
    BUEY_T6("https://render.albiononline.com/v1/item/T6_MOUNT_OX.png"),
    BUEY_T7("https://render.albiononline.com/v1/item/T7_MOUNT_OX.png"),
    BUEY_T8("https://render.albiononline.com/v1/item/T8_MOUNT_OX.png"),
    CIERVO_T4("https://render.albiononline.com/v1/item/T4_MOUNT_GIANTSTAG.png"),
    CABALLO_GUERRA_T5("https://render.albiononline.com/v1/item/T5_MOUNT_ARMORED_HORSE_SKIN_01.png"),
    CABALLO_GUERRA_T6("https://render.albiononline.com/v1/item/T6_MOUNT_ARMORED_HORSE_SKIN_01.png"),
    CABALLO_GUERRA_T7("https://render.albiononline.com/v1/item/T7_MOUNT_ARMORED_HORSE_SKIN_01.png"),
    CABALLO_GUERRA_T8("https://render.albiononline.com/v1/item/T8_MOUNT_ARMORED_HORSE_SKIN_01.png"),
    GARRAPRESTA_T5("https://render.albiononline.com/v1/item/T5_MOUNT_COUGAR_KEEPER@1.png"),
    GARRAFURIA_T8("https://render.albiononline.com/v1/item/T8_MOUNT_COUGAR_KEEPER@1.png"),
    OSO_INVIERNO_T5("https://render.albiononline.com/v1/item/T5_MOUNT_DIREBEAR_FW_FORTSTERLING.png"),
    JABALI_T5("https://render.albiononline.com/v1/item/T5_MOUNT_DIREBOAR_FW_LYMHURST.png"),
    LOBO_T5("https://render.albiononline.com/v1/item/T5_MOUNT_GREYWOLF_FW_CAERLEON.png"),
    AVE_MOA_T5("https://render.albiononline.com/v1/item/T5_MOUNT_MOABIRD_FW_BRIDGEWATCH.png"),
    BUHO_T5("https://render.albiononline.com/v1/item/T5_MOUNT_OWL_FW_BRECILIEN.png"),
    CARNERO_T5("https://render.albiononline.com/v1/item/T5_MOUNT_RAM_FW_MARTLOCK.png"),
    SALAMANDRA_T5("https://render.albiononline.com/v1/item/T5_MOUNT_SWAMPDRAGON_FW_THETFORD.png"),
    CABALLO_BLINDADO_T5("https://render.albiononline.com/v1/item/T5_MOUNT_ARMORED_HORSE.png"),
    CABALLO_BLINDADO_T6("https://render.albiononline.com/v1/item/T6_MOUNT_ARMORED_HORSE.png"),
    CABALLO_BLINDADO_T7("https://render.albiononline.com/v1/item/T7_MOUNT_ARMORED_HORSE.png"),
    CABALLO_BLINDADO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_ARMORED_HORSE.png"),
    HUARGO_T6("https://render.albiononline.com/v1/item/T6_MOUNT_DIREWOLF.png"),
    CARNERO_HIELO_T6("https://render.albiononline.com/v1/item/T6_MOUNT_FROSTRAM_ADC.png"),
    ALCE_T6("https://render.albiononline.com/v1/item/T6_MOUNT_GIANTSTAG_MOOSE.png"),
    BALISTA_T6("https://render.albiononline.com/v1/item/T6_MOUNT_SIEGE_BALLISTA.png"),
    BASILISCO_VENENOSO_T7("https://render.albiononline.com/v1/item/T7_MOUNT_ARMORED_SWAMPDRAGON_BATTLE.png"),
    JABALI_T7("https://render.albiononline.com/v1/item/T7_MOUNT_DIREBOAR.png"),
    HUSKY_T7("https://render.albiononline.com/v1/item/T7_MOUNT_HUSKY_ADC.png"),
    LAGARTIJA_PLAGA_T7("https://render.albiononline.com/v1/item/T7_MOUNT_MONITORLIZARD_ADC.png"),
    DRAGON_T7("https://render.albiononline.com/v1/item/T7_MOUNT_SWAMPDRAGON.png"),
    BASILISCO_AVALONIANO_T7("https://render.albiononline.com/v1/item/T7_MOUNT_SWAMPDRAGON_AVALON_BASILISK.png"),
    BASILISCO_FUEGO_T7("https://render.albiononline.com/v1/item/T7_MOUNT_SWAMPDRAGON_BATTLE.png"),
    AVE_TERROR_T7("https://render.albiononline.com/v1/item/T7_MOUNT_TERRORBIRD_ADC.png"),
    PESADILLA_MORGANA_T8("https://render.albiononline.com/v1/item/T8_MOUNT_ARMORED_HORSE_MORGANA@1.png"),
    OSO_GIGANTE_T8("https://render.albiononline.com/v1/item/T8_MOUNT_DIREBEAR.png"),
    OSO_INVIERNO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_DIREBEAR_FW_FORTSTERLING_ELITE.png"),
    JABALI_T8("https://render.albiononline.com/v1/item/T8_MOUNT_DIREBOAR_FW_LYMHURST_ELITE.png"),
    LOBO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_GREYWOLF_FW_CAERLEON_ELITE.png"),
    CABALLO_HUESUDO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_HORSE_UNDEAD@1.png"),
    MAMUT_COMANDO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_MAMMOTH_BATTLE@1.png"),
    MAMUT_TRANSPORTE_T8("https://render.albiononline.com/v1/item/T8_MOUNT_MAMMOTH_TRANSPORT.png"),
    AVE_TERROR_T8("https://render.albiononline.com/v1/item/T8_MOUNT_MOABIRD_FW_BRIDGEWATCH_ELITE.png"),
    BUHO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_OWL_FW_BRECILIEN_ELITE.png"),
    CARNERO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_RAM_FW_MARTLOCK_ELITE.png"),
    SALAMANDRA_T8("https://render.albiononline.com/v1/item/T8_MOUNT_SWAMPDRAGON_FW_THETFORD_ELITE.png"),
    AGUILA_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_ARMORED_EAGLE_CRYSTAL.png"),
    AGUILA_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_ARMORED_EAGLE_GOLD.png"),
    AGUILA_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_ARMORED_EAGLE_SILVER.png"),
    BASTION_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BASTION_CRYSTAL.png"),
    BASTION_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BASTION_GOLD.png"),
    BASTION_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BASTION_SILVER.png"),
    MURCIELAGO_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BAT_PERSONAL.png"),
    MUERCIELAGO_T3("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BAT_TELLAFRIEND.png"),
    GOLIAT_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BATTLESPIDER_CRYSTAL.png"),
    GOLIAT_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BATTLESPIDER_GOLD.png"),
    GOLIAT_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BATTLESPIDER_SILVER.png"),
    OSO_GRIZZLY_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BEAR_KEEPER_ADC.png"),
    ESCARABAJO_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BEETLE_CRYSTAL.png"),
    ESCARABAJO_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BEETLE_GOLD.png"),
    ESCARABAJO_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BEETLE_SILVER.png"),
    BEHEMOTH_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BEHEMOTH_CRYSTAL.png"),
    BEHEMOTH_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BEHEMOTH_GOLD.png"),
    BEHEMOTH_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BEHEMOTH_SILVER.png"),
    PANTERA_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_BLACK_PANTHER_ADC.png"),
    BUHO_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_DIVINE_OWL_ADC.png"),
    ENT_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_ENT_CRYSTAL.png"),
    ENT_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_ENT_GOLD.png"),
    ENT_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_ENT_SILVER.png"),
    CABALLO_GALLARDO_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_GIANT_HORSE_ADC.png"),
    SAPO_GIGANTE_T3("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_GIANTTOAD_02_TELLAFRIEND.png"),
    SAPO_T3("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_GIANTTOAD_TELLAFRIEND.png"),
    MULA_HEREJE_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_HERETIC_MULE_ADC.png"),
    JUGGERNAUT_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_JUGGERNAUT_CRYSTAL.png"),
    JUGGERNAUT_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_JUGGERNAUT_GOLD.png"),
    JUGGERNAUT_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_JUGGERNAUT_SILVER.png"),
    AVE_MOA_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_MOABIRD_TELLAFRIEND.png"),
    CUERVO_MORGANA_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_MORGANA_RAVEN_ADC.png"),
    CARNERO_T3("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_RAM_TELLAFRIEND.png"),
    ARIETE_YULE_T3("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_RAM_XMAS.png"),
    RINOCERONTE_T5("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_RHINO_SEASON_BRONZE.png"),
    RINOCERONTE_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_RHINO_SEASON_CRYSTAL.png"),
    RINOCERONTE_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_RHINO_SEASON_GOLD.png"),
    RINOCERONTE_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_RHINO_SEASON_SILVER.png"),
    ESCARABAJO_FALANGE_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_TANKBEETLE_CRYSTAL.png"),
    ESCARABAJO_FALANGE_T7("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_TANKBEETLE_GOLD.png"),
    ESCARABAJO_FALANGE_T6("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_TANKBEETLE_SILVER.png"),
    TORRE_MOVIL_T8("https://render.albiononline.com/v1/item/UNIQUE_MOUNT_TOWER_CHARIOT_CRYSTAL.png"),
    CONEJO_T8("https://render.albiononline.com/v1/item/T8_MOUNT_RABBIT_EASTER.png"),
    CONEJO_CARLEON_T8("https://render.albiononline.com/v1/item/T8_MOUNT_RABBIT_EASTER_DARK@1.png");

    private String ruta;

    private Imagen(String ruta) {
        this.ruta = ruta;
    }

    public String getRuta() {
        return ruta;
    }

    public static Imagen getRandomImagen() {
        Imagen[] values = Imagen.values();
        int randomIndex = (int) (Math.random() * values.length);
        return values[randomIndex];
    }
}